# Wheel files for ComfyUI-3D-Pack on Linux

According to:

https://github.com/MrForExample/ComfyUI-3D-Pack/blob/main/requirements_post.txt

## How to use

[source,sh]
----
git clone --depth=1 https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels.git

python3 -m pip install ComfyUI-3D-Pack-LinuxWheels/*.whl
----

## How to build

You need:

* Linux or Docker Desktop WSL2
* An NVIDIA GPU
* GPU driver installed on your host OS
* (For Linux hosts)
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html[NVIDIA Container Toolkit]
installed and configured

* (Linux Optional)
If you want to write a `Dockerfile` to build automatically,
you need to modify 
https://stackoverflow.com/questions/59691207/docker-build-with-nvidia-runtime[runtime settings]


### Run a container with dev environment

.Run with Docker
[source,bash]
----
docker run -it \
  --name builder \
  --gpus all \
  yanwk/comfyui-extras:devel-torch
----

OR

.Here's how I run with Podman
[source,bash]
----
podman run -it --rm \
  --name builder \
  --device nvidia.com/gpu=all \
  --security-opt label=disable \
  --user root --workdir /root \
  -e HTTP_PROXY=http://host.containers.internal:1081 \
  -e HTTPS_PROXY=http://host.containers.internal:1081 \
  yanwk/comfyui-extras:devel-torch
----

If you want to build the image yourself, you can find Dockerfile
https://github.com/YanWenKun/ComfyUI-Containerfiles/blob/main/dev-torch/Dockerfile[there]

### Build Command

* A side note, I also got this warning message:

====
simple-knn/spatial.cu:23:64: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. 
====

It's fine to leave it. But I fixed that anyway.

* I only used one compile target "6.1+PTX" to save build time. It should be running fine on Pascal and later GPUs.
You can add more if you want to squeeze more performance (not sure).

** https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/[Arch list]

[source,bash]
----
export TORCH_CUDA_ARCH_LIST="6.1+PTX"
----

* *[IMPORTANT]* Fix for nvcc 12.x
** Ref: https://github.com/pybind/pybind11/issues/4606
[source,bash]
----
sed -i "s/return caster.operator typename make_caster<T>::template cast_op_type<T>()/return caster/g" \
  /usr/lib64/python3.11/site-packages/torch/include/pybind11/cast.h
----

Finally we can move on compiling

[source,bash]
----
git clone --depth=1 --no-tags \
    https://github.com/MrForExample/ComfyUI-3D-Pack.git

cd ComfyUI-3D-Pack

pip install -r requirements.txt

pip wheel -w /root/tmp_wheels \
  ./tgs/models/snowflake/pointnet2_ops_lib

pip wheel -w /root/tmp_wheels \
 ./simple-knn

pip wheel -w /root/tmp_wheels \
 git+https://github.com/ashawkey/diff-gaussian-rasterization

pip wheel -w /root/tmp_wheels \
 git+https://github.com/NVlabs/nvdiffrast/

pip wheel -w /root/tmp_wheels \
 git+https://github.com/facebookresearch/pytorch3d.git@stable

pip wheel -w /root/tmp_wheels \
 git+https://github.com/rusty1s/pytorch_scatter.git

pip wheel -w /root/tmp_wheels \
 git+https://github.com/ashawkey/kiuikit.git

pip wheel -w /root/tmp_wheels \
 git+https://github.com/tatsy/torchmcubes.git

# This step is redundant, you can skip it
pip wheel -w /root/tmp_wheels \
 -r requirements_post.txt
----

### Copy wheels

Copy wheel files out of container, into current working folder

[source,bash]
----
docker cp builder:/root/tmp_wheels/ .
----

